{
  "bboxMode": 0,
  "collisionKind": 1,
  "type": 0,
  "origin": 9,
  "preMultiplyAlpha": false,
  "edgeFiltering": false,
  "collisionTolerance": 0,
  "swfPrecision": 2.525,
  "bbox_left": 0,
  "bbox_right": 205,
  "bbox_top": 2,
  "bbox_bottom": 93,
  "HTile": false,
  "VTile": false,
  "For3D": false,
  "width": 256,
  "height": 96,
  "textureGroupId": {
    "name": "Default",
    "path": "texturegroups/Default",
  },
  "swatchColours": null,
  "gridX": 0,
  "gridY": 0,
  "frames": [
    {"compositeImage":{"FrameId":{"name":"8fcecff0-ad3a-4b47-a107-199f1a34caf1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"8fcecff0-ad3a-4b47-a107-199f1a34caf1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"8fcecff0-ad3a-4b47-a107-199f1a34caf1","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"acdf8b97-a4c3-4f94-a2e3-883d7744191c","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"acdf8b97-a4c3-4f94-a2e3-883d7744191c","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"acdf8b97-a4c3-4f94-a2e3-883d7744191c","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"1e75b613-1712-4d06-8ff2-4160d39d6fe4","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"1e75b613-1712-4d06-8ff2-4160d39d6fe4","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"1e75b613-1712-4d06-8ff2-4160d39d6fe4","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"370f9bc0-87a3-415f-ae8d-29b58bd3bce6","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"370f9bc0-87a3-415f-ae8d-29b58bd3bce6","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"370f9bc0-87a3-415f-ae8d-29b58bd3bce6","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"8e10b2aa-2ad4-48bd-9355-55b2faedf8bb","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"8e10b2aa-2ad4-48bd-9355-55b2faedf8bb","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"8e10b2aa-2ad4-48bd-9355-55b2faedf8bb","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"7c6f1789-c559-42ad-bed8-90c9b9c7d0b1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"7c6f1789-c559-42ad-bed8-90c9b9c7d0b1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"7c6f1789-c559-42ad-bed8-90c9b9c7d0b1","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"acb217b5-79b9-494f-8cf3-f26532d25b40","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"acb217b5-79b9-494f-8cf3-f26532d25b40","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"acb217b5-79b9-494f-8cf3-f26532d25b40","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"6e7a693c-e874-42d2-bfac-d1fdfbdae15a","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"6e7a693c-e874-42d2-bfac-d1fdfbdae15a","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"6e7a693c-e874-42d2-bfac-d1fdfbdae15a","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a0acddb3-ce72-43f7-8a67-a16f7757c396","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a0acddb3-ce72-43f7-8a67-a16f7757c396","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"a0acddb3-ce72-43f7-8a67-a16f7757c396","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"75c3717b-40c6-4484-a993-ea0b847d3c70","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"75c3717b-40c6-4484-a993-ea0b847d3c70","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"75c3717b-40c6-4484-a993-ea0b847d3c70","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"e36ad3ec-21c7-4682-87ab-8e82640da930","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"e36ad3ec-21c7-4682-87ab-8e82640da930","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"e36ad3ec-21c7-4682-87ab-8e82640da930","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"59b2d65a-66a8-43be-b4cb-ae93a771f429","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"59b2d65a-66a8-43be-b4cb-ae93a771f429","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"59b2d65a-66a8-43be-b4cb-ae93a771f429","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d431d264-ff2a-4cb7-85fd-1b941675d665","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d431d264-ff2a-4cb7-85fd-1b941675d665","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"d431d264-ff2a-4cb7-85fd-1b941675d665","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"733cd2df-2d00-480b-876f-e26ff59ece11","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"733cd2df-2d00-480b-876f-e26ff59ece11","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"733cd2df-2d00-480b-876f-e26ff59ece11","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c84c3d98-236d-40e1-a21f-a0331cafc751","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c84c3d98-236d-40e1-a21f-a0331cafc751","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"c84c3d98-236d-40e1-a21f-a0331cafc751","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a87e5e56-8ca7-49e7-979c-0c6bb08486ec","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a87e5e56-8ca7-49e7-979c-0c6bb08486ec","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"a87e5e56-8ca7-49e7-979c-0c6bb08486ec","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"2becc14d-6bfb-411a-9162-e7d3d848fe85","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"2becc14d-6bfb-411a-9162-e7d3d848fe85","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"2becc14d-6bfb-411a-9162-e7d3d848fe85","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"5e8841ad-2410-4ce3-9596-6a49e201d5a1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"5e8841ad-2410-4ce3-9596-6a49e201d5a1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"5e8841ad-2410-4ce3-9596-6a49e201d5a1","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"7c840c78-d6ef-4954-a644-de6efdbd2840","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"7c840c78-d6ef-4954-a644-de6efdbd2840","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"7c840c78-d6ef-4954-a644-de6efdbd2840","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"3ae3425d-0954-49dc-b30f-2229508e6cf0","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"3ae3425d-0954-49dc-b30f-2229508e6cf0","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"3ae3425d-0954-49dc-b30f-2229508e6cf0","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"3cc3be69-0fd5-4239-a598-8000c5290cc1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"3cc3be69-0fd5-4239-a598-8000c5290cc1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"3cc3be69-0fd5-4239-a598-8000c5290cc1","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"2cfa76d9-0269-435e-9861-21d5304ceea2","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"2cfa76d9-0269-435e-9861-21d5304ceea2","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"2cfa76d9-0269-435e-9861-21d5304ceea2","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"f23a4fb4-ddd0-409b-acac-00954bcfda2d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"f23a4fb4-ddd0-409b-acac-00954bcfda2d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"f23a4fb4-ddd0-409b-acac-00954bcfda2d","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"4a9ad8ee-d3ac-4c84-8658-07aa42b34c4d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"4a9ad8ee-d3ac-4c84-8658-07aa42b34c4d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"4a9ad8ee-d3ac-4c84-8658-07aa42b34c4d","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"32a668d4-3a43-421f-9e45-99b047b70edc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"32a668d4-3a43-421f-9e45-99b047b70edc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"32a668d4-3a43-421f-9e45-99b047b70edc","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a0380119-c29e-4f10-a449-99744cd448ec","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a0380119-c29e-4f10-a449-99744cd448ec","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"a0380119-c29e-4f10-a449-99744cd448ec","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"f2d39147-31af-47e6-b94b-8c1f4e699709","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"f2d39147-31af-47e6-b94b-8c1f4e699709","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"f2d39147-31af-47e6-b94b-8c1f4e699709","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"1c46d263-e5ac-407a-aa5e-f0af64fbc8dc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"1c46d263-e5ac-407a-aa5e-f0af64fbc8dc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"1c46d263-e5ac-407a-aa5e-f0af64fbc8dc","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"8540ffd4-508e-4dcd-8198-de4c52d448bf","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"8540ffd4-508e-4dcd-8198-de4c52d448bf","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"8540ffd4-508e-4dcd-8198-de4c52d448bf","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"f4e14946-6734-4c7f-aaa3-477e282cb392","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"f4e14946-6734-4c7f-aaa3-477e282cb392","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"f4e14946-6734-4c7f-aaa3-477e282cb392","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"db52a4d1-825f-40a7-971f-99580e86186d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"db52a4d1-825f-40a7-971f-99580e86186d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"db52a4d1-825f-40a7-971f-99580e86186d","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"55149cbe-b818-42b3-8abd-61b5c4018a45","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"55149cbe-b818-42b3-8abd-61b5c4018a45","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"55149cbe-b818-42b3-8abd-61b5c4018a45","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"adb594d0-af29-46a0-a446-3e1cb114746e","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"adb594d0-af29-46a0-a446-3e1cb114746e","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"adb594d0-af29-46a0-a446-3e1cb114746e","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"23651937-4e80-4d55-b7c5-a40630908ccc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"23651937-4e80-4d55-b7c5-a40630908ccc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"23651937-4e80-4d55-b7c5-a40630908ccc","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"66a8d3be-0e1a-421b-bc9c-8265c016aa41","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"66a8d3be-0e1a-421b-bc9c-8265c016aa41","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"66a8d3be-0e1a-421b-bc9c-8265c016aa41","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c1fe6bad-9689-43fb-a529-517da65b5e9b","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c1fe6bad-9689-43fb-a529-517da65b5e9b","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"c1fe6bad-9689-43fb-a529-517da65b5e9b","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"37b99df4-6c23-40cb-94e6-bbac115649a9","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"37b99df4-6c23-40cb-94e6-bbac115649a9","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"37b99df4-6c23-40cb-94e6-bbac115649a9","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"bf9a4a6b-bdde-4b3e-92cd-07c5a4c20c06","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"bf9a4a6b-bdde-4b3e-92cd-07c5a4c20c06","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"bf9a4a6b-bdde-4b3e-92cd-07c5a4c20c06","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a6b299a0-6b86-474c-a6f2-f76bc98bd9e8","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a6b299a0-6b86-474c-a6f2-f76bc98bd9e8","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"LayerId":{"name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","name":"a6b299a0-6b86-474c-a6f2-f76bc98bd9e8","tags":[],"resourceType":"GMSpriteFrame",},
  ],
  "sequence": {
    "spriteId": {"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},
    "timeUnits": 1,
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "autoRecord": true,
    "volume": 1.0,
    "length": 39.0,
    "events": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MessageEventKeyframe>",},
    "moments": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MomentsEventKeyframe>",},
    "tracks": [
      {"name":"frames","spriteId":null,"keyframes":{"Keyframes":[
            {"id":"e64cc829-f5b4-4288-9b7f-8b3957bd98b9","Key":0.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"8fcecff0-ad3a-4b47-a107-199f1a34caf1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"a8e2b4ab-05d6-4fac-90fa-0e77bd25a70b","Key":1.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"acdf8b97-a4c3-4f94-a2e3-883d7744191c","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"939f395a-243d-4348-9de3-88b8419f5e1c","Key":2.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"1e75b613-1712-4d06-8ff2-4160d39d6fe4","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d5d6c0ec-4720-4ba1-8e06-22226bdb3bb2","Key":3.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"370f9bc0-87a3-415f-ae8d-29b58bd3bce6","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c22a2f85-31b6-44b4-a2c7-424baa2a5d08","Key":4.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"8e10b2aa-2ad4-48bd-9355-55b2faedf8bb","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"b84f9c5a-3e97-4bc1-b620-84e343251d8f","Key":5.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"7c6f1789-c559-42ad-bed8-90c9b9c7d0b1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"6315bc46-22fa-4a63-bc89-656e1feae2fa","Key":6.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"acb217b5-79b9-494f-8cf3-f26532d25b40","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"1e14e9d7-9e4e-45da-b75c-5d4b676f4c09","Key":7.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"6e7a693c-e874-42d2-bfac-d1fdfbdae15a","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"3373d642-fc03-4ea3-a92f-1ccb97c9f3fc","Key":8.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a0acddb3-ce72-43f7-8a67-a16f7757c396","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d3448d0d-0a6f-4c24-8c25-93b83f0415cf","Key":9.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"75c3717b-40c6-4484-a993-ea0b847d3c70","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"fe6dbc2b-7c4f-440e-afc8-8bada1d2410b","Key":10.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"e36ad3ec-21c7-4682-87ab-8e82640da930","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"7ba93002-5d0e-4784-b735-3122a15f7b11","Key":11.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"59b2d65a-66a8-43be-b4cb-ae93a771f429","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"ca50226c-c12e-4ce6-aefa-182d225650ea","Key":12.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d431d264-ff2a-4cb7-85fd-1b941675d665","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"269cfcfa-500f-4b85-97ce-5218678f21b6","Key":13.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"733cd2df-2d00-480b-876f-e26ff59ece11","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"75cd28fa-b53e-424c-b770-d3026aa0a3a4","Key":14.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c84c3d98-236d-40e1-a21f-a0331cafc751","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"7813d060-2a65-414d-a9bd-9939439e9a59","Key":15.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a87e5e56-8ca7-49e7-979c-0c6bb08486ec","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"2e5dee87-74e2-4540-b0b2-9cd86269d0d5","Key":16.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"2becc14d-6bfb-411a-9162-e7d3d848fe85","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"2ae9927b-18bd-41b3-8e64-832dcb29ddd5","Key":17.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"5e8841ad-2410-4ce3-9596-6a49e201d5a1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"7f3a1e01-7d92-47d7-b63d-5a90836a6abd","Key":18.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"7c840c78-d6ef-4954-a644-de6efdbd2840","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"5f40ea05-3944-47d0-a8d6-c8e8f38ce951","Key":19.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"3ae3425d-0954-49dc-b30f-2229508e6cf0","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"4179edfe-14d3-45c2-9ed6-e7415553cbbe","Key":20.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"3cc3be69-0fd5-4239-a598-8000c5290cc1","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d4e0b0d1-25c2-4171-8c5d-d53eef039054","Key":21.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"2cfa76d9-0269-435e-9861-21d5304ceea2","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"2c626758-0997-437c-ac25-9cef73f55a80","Key":22.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"f23a4fb4-ddd0-409b-acac-00954bcfda2d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c5058939-0704-4b43-93ec-3ef0de866b6c","Key":23.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"4a9ad8ee-d3ac-4c84-8658-07aa42b34c4d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"29602567-1818-4aa1-86b9-43cbebc72608","Key":24.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"32a668d4-3a43-421f-9e45-99b047b70edc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"597a29b1-4bcd-45bd-ba5a-6655f608c63b","Key":25.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a0380119-c29e-4f10-a449-99744cd448ec","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"f2d133a4-a509-4b41-8748-4545c8021a74","Key":26.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"f2d39147-31af-47e6-b94b-8c1f4e699709","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"0dd07043-c86a-4d88-9831-685ea3625b77","Key":27.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"1c46d263-e5ac-407a-aa5e-f0af64fbc8dc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9bb83631-4c85-4c5f-b4e4-14a756cec07c","Key":28.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"8540ffd4-508e-4dcd-8198-de4c52d448bf","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"57cd4cd9-fe80-4755-b410-03f2c0844df0","Key":29.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"f4e14946-6734-4c7f-aaa3-477e282cb392","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"6da036be-bac9-48e1-b406-b4b4a175aa0d","Key":30.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"db52a4d1-825f-40a7-971f-99580e86186d","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"68575451-10f8-4103-9251-ae6b5bb9ff6e","Key":31.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"55149cbe-b818-42b3-8abd-61b5c4018a45","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"e7902695-0c53-443e-a422-9da86c4be0e1","Key":32.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"adb594d0-af29-46a0-a446-3e1cb114746e","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c2951813-6851-4c45-a9e8-261fa97008a1","Key":33.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"23651937-4e80-4d55-b7c5-a40630908ccc","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"534ce68c-48c6-412b-a0e7-1c94146464a3","Key":34.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"66a8d3be-0e1a-421b-bc9c-8265c016aa41","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"82136c19-63e0-4ffa-a8ad-d6df3b337dbf","Key":35.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c1fe6bad-9689-43fb-a529-517da65b5e9b","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"926e380c-6a37-4a05-b60d-b97f28b7fc4d","Key":36.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"37b99df4-6c23-40cb-94e6-bbac115649a9","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"94959de1-bd77-45d5-abcd-37b8fe6348e4","Key":37.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"bf9a4a6b-bdde-4b3e-92cd-07c5a4c20c06","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"2b16d0b6-f8f5-44ba-9467-0f13e24e770c","Key":38.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a6b299a0-6b86-474c-a6f2-f76bc98bd9e8","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
          ],"resourceVersion":"1.0","resourceType":"KeyframeStore<SpriteFrameKeyframe>",},"trackColour":0,"inheritsTrackColour":true,"builtinName":0,"traits":0,"interpolation":1,"tracks":[],"events":[],"modifiers":[],"isCreationTrack":false,"resourceVersion":"1.0","tags":[],"resourceType":"GMSpriteFramesTrack",},
    ],
    "visibleRange": {"x":0.0,"y":0.0,},
    "lockOrigin": true,
    "showBackdrop": true,
    "showBackdropImage": false,
    "backdropImagePath": "",
    "backdropImageOpacity": 0.5,
    "backdropWidth": 1920,
    "backdropHeight": 1080,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "xorigin": 31,
    "yorigin": 88,
    "eventToFunction": {},
    "eventStubScript": null,
    "parent": {"name":"spr_flame_brawler_attack_blazing_rush_placeholder","path":"sprites/spr_flame_brawler_attack_blazing_rush_placeholder/spr_flame_brawler_attack_blazing_rush_placeholder.yy",},
    "resourceVersion": "1.3",
    "name": "",
    "tags": [],
    "resourceType": "GMSequence",
  },
  "layers": [
    {"visible":true,"isLocked":false,"blendMode":0,"opacity":100.0,"displayName":"default","resourceVersion":"1.0","name":"0be83bac-8bc3-4b4c-8d43-24c506b4dc42","tags":[],"resourceType":"GMImageLayer",},
  ],
  "parent": {
    "name": "flame brawler",
    "path": "folders/Sprites/Sand Alliance/units/flame brawler.yy",
  },
  "resourceVersion": "1.0",
  "name": "spr_flame_brawler_attack_blazing_rush_placeholder",
  "tags": [],
  "resourceType": "GMSprite",
}