{
  "bboxMode": 0,
  "collisionKind": 1,
  "type": 0,
  "origin": 9,
  "preMultiplyAlpha": false,
  "edgeFiltering": false,
  "collisionTolerance": 0,
  "swfPrecision": 2.525,
  "bbox_left": 8,
  "bbox_right": 231,
  "bbox_top": 28,
  "bbox_bottom": 91,
  "HTile": false,
  "VTile": false,
  "For3D": false,
  "width": 320,
  "height": 96,
  "textureGroupId": {
    "name": "Default",
    "path": "texturegroups/Default",
  },
  "swatchColours": null,
  "gridX": 0,
  "gridY": 0,
  "frames": [
    {"compositeImage":{"FrameId":{"name":"0a9d981c-bf1f-4b11-8404-67752ea05f1b","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"0a9d981c-bf1f-4b11-8404-67752ea05f1b","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"0a9d981c-bf1f-4b11-8404-67752ea05f1b","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"bf2a1dd3-aae8-4c34-83b9-16025498df98","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"bf2a1dd3-aae8-4c34-83b9-16025498df98","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"bf2a1dd3-aae8-4c34-83b9-16025498df98","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"7f463325-84ac-49db-82a2-4726ab393fec","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"7f463325-84ac-49db-82a2-4726ab393fec","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"7f463325-84ac-49db-82a2-4726ab393fec","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"e2ff2aaf-7eb6-4017-a919-638b6087b78f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"e2ff2aaf-7eb6-4017-a919-638b6087b78f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"e2ff2aaf-7eb6-4017-a919-638b6087b78f","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"59588393-6f3c-4a7c-9e73-f3385df1b227","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"59588393-6f3c-4a7c-9e73-f3385df1b227","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"59588393-6f3c-4a7c-9e73-f3385df1b227","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d35d7ce0-e4b2-4d45-aaac-676e99f26f0f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d35d7ce0-e4b2-4d45-aaac-676e99f26f0f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"d35d7ce0-e4b2-4d45-aaac-676e99f26f0f","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"3668981d-c736-4a68-a6e6-40c6d5e5945c","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"3668981d-c736-4a68-a6e6-40c6d5e5945c","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"3668981d-c736-4a68-a6e6-40c6d5e5945c","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"e20a8c3e-1526-4be7-940b-b1fb0a44cf6d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"e20a8c3e-1526-4be7-940b-b1fb0a44cf6d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"e20a8c3e-1526-4be7-940b-b1fb0a44cf6d","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"f1ef18fe-75da-49db-84af-76c08825fc6c","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"f1ef18fe-75da-49db-84af-76c08825fc6c","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"f1ef18fe-75da-49db-84af-76c08825fc6c","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"539f6a64-f87d-4930-b2b4-bedaf3989aab","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"539f6a64-f87d-4930-b2b4-bedaf3989aab","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"539f6a64-f87d-4930-b2b4-bedaf3989aab","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"44ae4389-09d6-4a3b-aa7e-58fc43347e25","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"44ae4389-09d6-4a3b-aa7e-58fc43347e25","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"44ae4389-09d6-4a3b-aa7e-58fc43347e25","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"ff52b648-958e-4ddb-8c00-354b897eb82f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"ff52b648-958e-4ddb-8c00-354b897eb82f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"ff52b648-958e-4ddb-8c00-354b897eb82f","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"1d0c6cec-96ef-4ea8-b676-d62993f7d2ca","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"1d0c6cec-96ef-4ea8-b676-d62993f7d2ca","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"1d0c6cec-96ef-4ea8-b676-d62993f7d2ca","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"ffbf620f-0690-4852-a8e7-5c00a5a78b8d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"ffbf620f-0690-4852-a8e7-5c00a5a78b8d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"ffbf620f-0690-4852-a8e7-5c00a5a78b8d","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"26d747ff-bb5b-42db-968e-d7b198d19597","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"26d747ff-bb5b-42db-968e-d7b198d19597","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"26d747ff-bb5b-42db-968e-d7b198d19597","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"2ccb67d4-df1f-4cc5-897b-5271fbd43810","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"2ccb67d4-df1f-4cc5-897b-5271fbd43810","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"2ccb67d4-df1f-4cc5-897b-5271fbd43810","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"7bc8f758-ace8-4d15-af7d-e4dd8f304a29","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"7bc8f758-ace8-4d15-af7d-e4dd8f304a29","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"7bc8f758-ace8-4d15-af7d-e4dd8f304a29","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c2d98951-5b8c-4047-8fd3-8255bef04147","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c2d98951-5b8c-4047-8fd3-8255bef04147","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"c2d98951-5b8c-4047-8fd3-8255bef04147","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"46f00ce7-dedb-47d8-b868-0ff21826db1b","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"46f00ce7-dedb-47d8-b868-0ff21826db1b","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"46f00ce7-dedb-47d8-b868-0ff21826db1b","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"1eaa3616-52f9-4ae4-b2e0-6ad10b25d6af","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"1eaa3616-52f9-4ae4-b2e0-6ad10b25d6af","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"1eaa3616-52f9-4ae4-b2e0-6ad10b25d6af","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"47d12a00-88cc-48cd-be09-d7db30966580","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"47d12a00-88cc-48cd-be09-d7db30966580","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"47d12a00-88cc-48cd-be09-d7db30966580","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"ba37ae13-da9c-41d6-9916-0edc98fbbe42","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"ba37ae13-da9c-41d6-9916-0edc98fbbe42","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"ba37ae13-da9c-41d6-9916-0edc98fbbe42","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"48845e08-445e-48f3-acc8-3afa5fa202d6","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"48845e08-445e-48f3-acc8-3afa5fa202d6","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"48845e08-445e-48f3-acc8-3afa5fa202d6","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"063d1e5f-d978-4d07-abda-3b1b1481c727","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"063d1e5f-d978-4d07-abda-3b1b1481c727","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"063d1e5f-d978-4d07-abda-3b1b1481c727","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"bbd91595-6cee-4f1b-890b-596c8bf85581","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":null,"resourceVersion":"1.0","name":"composite","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"bbd91595-6cee-4f1b-890b-596c8bf85581","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"LayerId":{"name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","name":"bbd91595-6cee-4f1b-890b-596c8bf85581","tags":[],"resourceType":"GMSpriteFrame",},
  ],
  "sequence": {
    "spriteId": {"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},
    "timeUnits": 1,
    "playback": 1,
    "playbackSpeed": 10.0,
    "playbackSpeedType": 0,
    "autoRecord": true,
    "volume": 1.0,
    "length": 25.0,
    "events": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MessageEventKeyframe>",},
    "moments": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MomentsEventKeyframe>",},
    "tracks": [
      {"name":"frames","spriteId":null,"keyframes":{"Keyframes":[
            {"id":"3eb4a965-be13-4dc8-8fa3-17378ea8d5e0","Key":0.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"0a9d981c-bf1f-4b11-8404-67752ea05f1b","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"7d4e9849-e625-4c58-b895-8c3f06122a4a","Key":1.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"bf2a1dd3-aae8-4c34-83b9-16025498df98","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"fc005bf4-5249-499d-a79e-ea6b6dde0260","Key":2.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"7f463325-84ac-49db-82a2-4726ab393fec","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"db5024f7-0ee9-4ac8-868b-92cc8da1fcf2","Key":3.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"e2ff2aaf-7eb6-4017-a919-638b6087b78f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"4ee4bbd9-9348-40d6-bb12-7060f069079f","Key":4.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"59588393-6f3c-4a7c-9e73-f3385df1b227","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"e3746541-1a35-42ca-a836-8624250e70c5","Key":5.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d35d7ce0-e4b2-4d45-aaac-676e99f26f0f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"27486340-fa8b-4037-89f9-ce24d0679297","Key":6.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"3668981d-c736-4a68-a6e6-40c6d5e5945c","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"a7f8e0e2-cd72-4bc4-ae7f-30bb8c3d91aa","Key":7.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"e20a8c3e-1526-4be7-940b-b1fb0a44cf6d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"81ca883b-09d9-4826-a574-6837b9127d40","Key":8.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"f1ef18fe-75da-49db-84af-76c08825fc6c","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"96411540-97cd-4451-a14c-ef0ec0f57fce","Key":9.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"539f6a64-f87d-4930-b2b4-bedaf3989aab","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"5d5291c4-39b1-45dd-a30e-3f737c03aaca","Key":10.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"44ae4389-09d6-4a3b-aa7e-58fc43347e25","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d0c8a471-44db-41fe-86d2-529f03a8044f","Key":11.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"ff52b648-958e-4ddb-8c00-354b897eb82f","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"f0ffbe25-de9b-4fbe-a3a2-004bf07a391a","Key":12.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"1d0c6cec-96ef-4ea8-b676-d62993f7d2ca","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"26b99b04-b333-4e09-aad6-d318c003ce72","Key":13.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"ffbf620f-0690-4852-a8e7-5c00a5a78b8d","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"f536a668-c50c-47c0-aa04-65035d016b82","Key":14.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"26d747ff-bb5b-42db-968e-d7b198d19597","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"7f207fd8-a0fb-456b-9ddb-4da47b03f155","Key":15.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"2ccb67d4-df1f-4cc5-897b-5271fbd43810","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"0559efb0-8746-4e5a-8b31-87278814b2e7","Key":16.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"7bc8f758-ace8-4d15-af7d-e4dd8f304a29","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"49c68312-dfda-4ad1-abd4-10937c733242","Key":17.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c2d98951-5b8c-4047-8fd3-8255bef04147","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"70586871-149f-4eac-a0ac-e2ef7197fc7e","Key":18.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"46f00ce7-dedb-47d8-b868-0ff21826db1b","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"25838971-24d8-4cca-9689-6485718f4075","Key":19.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"1eaa3616-52f9-4ae4-b2e0-6ad10b25d6af","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"316dd60c-c5fd-412b-9619-59353b2c0d55","Key":20.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"47d12a00-88cc-48cd-be09-d7db30966580","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"f2ed2f25-3f7a-4517-a0e0-227f645c0fb2","Key":21.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"ba37ae13-da9c-41d6-9916-0edc98fbbe42","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"4c7eb883-0d66-4d4d-9fb2-f74d70104d65","Key":22.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"48845e08-445e-48f3-acc8-3afa5fa202d6","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9afcf1ee-6a87-4ba8-884c-d64b0efedf9f","Key":23.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"063d1e5f-d978-4d07-abda-3b1b1481c727","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"8b11cbfa-f3ea-4740-93be-e6e82f5474fe","Key":24.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"bbd91595-6cee-4f1b-890b-596c8bf85581","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
          ],"resourceVersion":"1.0","resourceType":"KeyframeStore<SpriteFrameKeyframe>",},"trackColour":0,"inheritsTrackColour":true,"builtinName":0,"traits":0,"interpolation":1,"tracks":[],"events":[],"modifiers":[],"isCreationTrack":false,"resourceVersion":"1.0","tags":[],"resourceType":"GMSpriteFramesTrack",},
    ],
    "visibleRange": {"x":0.0,"y":0.0,},
    "lockOrigin": false,
    "showBackdrop": true,
    "showBackdropImage": false,
    "backdropImagePath": "",
    "backdropImageOpacity": 0.5,
    "backdropWidth": 1920,
    "backdropHeight": 1080,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "xorigin": 30,
    "yorigin": 91,
    "eventToFunction": {},
    "eventStubScript": null,
    "parent": {"name":"spr_bolt_knight_attack_blast_placeholder","path":"sprites/spr_bolt_knight_attack_blast_placeholder/spr_bolt_knight_attack_blast_placeholder.yy",},
    "resourceVersion": "1.3",
    "name": "",
    "tags": [],
    "resourceType": "GMSequence",
  },
  "layers": [
    {"visible":true,"isLocked":false,"blendMode":0,"opacity":100.0,"displayName":"default","resourceVersion":"1.0","name":"6ef70b81-d7bf-41b9-af0e-0392b2be660d","tags":[],"resourceType":"GMImageLayer",},
  ],
  "parent": {
    "name": "bolt_knight",
    "path": "folders/Sprites/House Of Storms/units/bolt_knight.yy",
  },
  "resourceVersion": "1.0",
  "name": "spr_bolt_knight_attack_blast_placeholder",
  "tags": [],
  "resourceType": "GMSprite",
}